name = "datastar_lustre"
version = "3.0.1"

description = "Lustre bindings for Datastar"
licences = ["MIT"]
repository = { type = "github", user = "sporto", repo = "gleam-datastar" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.0.3 and < 6.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
